name: Yaml Lint
on: [push]  # yamllint disable-line rule:truthy
jobs:
  lintAllTheThings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout new code
        uses: actions/checkout@v3
          
      - name: Run yaml-lint
        uses: ibiqlik/action-yamllint@v3
